server:
  port: 9080


spring:
  cloud:
    gateway:
      metrics:
        enabled: true



logging:
  level:
    #org.springframework.cloud.gateway: DEBUG
    #org.springframework.http.server.reactive: DEBUG
    #org.springframework.web.reactive: DEBUG
    #org.springframework.boot.autoconfigure.web: DEBUG
    #reactor.netty: DEBUG
    #org.springframework.web.client.RestTemplate: DEBUG
    #org.springframework.security: DEBUG

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'
