server:
  port: 9080


spring:
  cloud:
    gateway:
      metrics:
        enabled: true



logging:
  level:
    org.springframework.cloud.gateway: WARN
    org.springframework.http.server.reactive: WARN
    org.springframework.web.reactive: WARN
    org.springframework.boot.autoconfigure.web: WARN
    reactor.netty: WARN
    org.springframework.web.client.RestTemplate: WARN
    org.springframework.security: WARN

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'
